"""initial schema

Revision ID: 4b866e29e2fc
Revises: 
Create Date: 2026-06-01 03:25:01.607166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b866e29e2fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=150), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('local_path', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_asset_type'), ['asset_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_assets_date_created', ['date_created'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_title'), ['title'], unique=False)
        batch_op.create_index('ix_assets_type_created_at', ['asset_type', 'created_at'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_slug'), ['slug'], unique=True)

    op.create_table('asset_tags',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', 'tag_id')
    )
    with op.batch_alter_table('asset_tags', schema=None) as batch_op:
        batch_op.create_index('ix_asset_tags_tag_asset', ['tag_id', 'asset_id'], unique=False)

    op.create_table('timeline_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timeline_events_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_timeline_events_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_timeline_events_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_timeline_events_year'), ['year'], unique=False)
        batch_op.create_index('ix_timeline_events_year_event_date', ['year', 'event_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.drop_index('ix_timeline_events_year_event_date')
        batch_op.drop_index(batch_op.f('ix_timeline_events_year'))
        batch_op.drop_index(batch_op.f('ix_timeline_events_title'))
        batch_op.drop_index(batch_op.f('ix_timeline_events_event_date'))
        batch_op.drop_index(batch_op.f('ix_timeline_events_asset_id'))

    op.drop_table('timeline_events')
    with op.batch_alter_table('asset_tags', schema=None) as batch_op:
        batch_op.drop_index('ix_asset_tags_tag_asset')

    op.drop_table('asset_tags')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_slug'))

    op.drop_table('tags')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index('ix_assets_type_created_at')
        batch_op.drop_index(batch_op.f('ix_assets_title'))
        batch_op.drop_index(batch_op.f('ix_assets_source'))
        batch_op.drop_index(batch_op.f('ix_assets_description'))
        batch_op.drop_index('ix_assets_date_created')
        batch_op.drop_index(batch_op.f('ix_assets_created_at'))
        batch_op.drop_index(batch_op.f('ix_assets_asset_type'))

    op.drop_table('assets')
    # ### end Alembic commands ###
